#############################################################################
# Makefile for building: libyr_sd_runtime_verif.a
# Generated by qmake (3.1) (Qt 5.15.2)
# Project:  yr_sd_runtime_verif.pro
# Template: lib
# Command: /usr/lib/qt5/bin/qmake -o Makefile yr_sd_runtime_verif.pro
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DUSE_GVGRAPH -DUSE_GVGRAPH -DQT_NO_DEBUG -DQT_OPENGL_LIB -DQT_PRINTSUPPORT_LIB -DQT_SVG_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_SQL_LIB -DQT_XML_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -fPIC -Wall -Wextra -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -Wno-unused-variable -Wno-unused-parameter -Wno-misleading-indentation -isystem -Wno-unused-variable -Wno-unused-parameter -Wno-misleading-indentation -isystem -O2 -fPIC -std=gnu++1y -Wall -Wextra -D_REENTRANT $(DEFINES)
INCPATH       = -I. -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtOpenGL -I/usr/include/x86_64-linux-gnu/qt5/QtPrintSupport -I/usr/include/x86_64-linux-gnu/qt5/QtSvg -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtXml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I_generated -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++
QMAKE         = /usr/lib/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/lib/qt5/bin/qmake -install qinstall
QINSTALL_PROGRAM = /usr/lib/qt5/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = yr_sd_runtime_verif1.0.0
DISTDIR = /home/yer/yr_sd_runtime_verif/_generated/yr_sd_runtime_verif1.0.0
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = _generated/

####### Files

SOURCES       = src/YR_CPP_MONITOR.cpp \
		src/YR_CPP_MONITOR_EDGE.cpp \
		src/YR_CPP_MONITOR_EVENT.cpp \
		src/YR_CPP_MONITOR_object.cpp \
		src/YR_CPP_MONITOR_STATE.cpp \
		src/YR_CPP_MONITOR_TRACE_EVENT.cpp \
		src/utils/YR_CPP_MONITOR_ERP-database.cpp \
		src/utils/YR_CPP_UTILS.cpp \
		src/yr-expressions-conditions/YR_CPP_BOOLEAN_expression.CPP \
		src/yr-expressions-conditions/YR_CPP_expression.CPP \
		src/yr-expressions-conditions/YR_CPP_in_SET_TRACE_expression.CPP \
		src/yr-expressions-conditions/YR_CPP_not_in_SET_TRACE_expression.CPP _generated/moc_YR_CPP_MONITOR.cpp \
		_generated/moc_YR_CPP_MONITOR_EDGE.cpp \
		_generated/moc_YR_CPP_MONITOR_EVENT.cpp \
		_generated/moc_YR_CPP_MONITOR_object.cpp \
		_generated/moc_YR_CPP_MONITOR_STATE.cpp \
		_generated/moc_YR_CPP_MONITOR_TRACE_EVENT.cpp \
		_generated/moc_YR_CPP_UTILS.cpp
OBJECTS       = _generated/YR_CPP_MONITOR.o \
		_generated/YR_CPP_MONITOR_EDGE.o \
		_generated/YR_CPP_MONITOR_EVENT.o \
		_generated/YR_CPP_MONITOR_object.o \
		_generated/YR_CPP_MONITOR_STATE.o \
		_generated/YR_CPP_MONITOR_TRACE_EVENT.o \
		_generated/YR_CPP_MONITOR_ERP-database.o \
		_generated/YR_CPP_UTILS.o \
		_generated/YR_CPP_BOOLEAN_expression.o \
		_generated/YR_CPP_expression.o \
		_generated/YR_CPP_in_SET_TRACE_expression.o \
		_generated/YR_CPP_not_in_SET_TRACE_expression.o \
		_generated/moc_YR_CPP_MONITOR.o \
		_generated/moc_YR_CPP_MONITOR_EDGE.o \
		_generated/moc_YR_CPP_MONITOR_EVENT.o \
		_generated/moc_YR_CPP_MONITOR_object.o \
		_generated/moc_YR_CPP_MONITOR_STATE.o \
		_generated/moc_YR_CPP_MONITOR_TRACE_EVENT.o \
		_generated/moc_YR_CPP_UTILS.o
DIST          = /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_charts.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_designer.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_help.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmlmodels.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_svg.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uitools.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_x11extras.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		config.pri \
		lib.pri \
		yr_sd_runtime_verif.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		yr_sd_runtime_verif.pro src/YR_CPP_MONITOR.hpp \
		src/YR_CPP_MONITOR_EDGE.hpp \
		src/YR_CPP_MONITOR_EVENT.hpp \
		src/YR_CPP_MONITOR_object.hpp \
		src/YR_CPP_MONITOR_STATE.hpp \
		src/YR_CPP_MONITOR_TRACE_EVENT.hpp \
		src/utils/YR_CPP_MONITOR_ERP-database.hpp \
		src/utils/YR_CPP_UTILS.hpp \
		src/yr-expressions-conditions/YR_CPP_BOOLEAN_expression.HPP \
		src/yr-expressions-conditions/YR_CPP_expression.HPP \
		src/yr-expressions-conditions/YR_CPP_in_SET_TRACE_expression.HPP \
		src/yr-expressions-conditions/YR_CPP_not_in_SET_TRACE_expression.HPP src/YR_CPP_MONITOR.cpp \
		src/YR_CPP_MONITOR_EDGE.cpp \
		src/YR_CPP_MONITOR_EVENT.cpp \
		src/YR_CPP_MONITOR_object.cpp \
		src/YR_CPP_MONITOR_STATE.cpp \
		src/YR_CPP_MONITOR_TRACE_EVENT.cpp \
		src/utils/YR_CPP_MONITOR_ERP-database.cpp \
		src/utils/YR_CPP_UTILS.cpp \
		src/yr-expressions-conditions/YR_CPP_BOOLEAN_expression.CPP \
		src/yr-expressions-conditions/YR_CPP_expression.CPP \
		src/yr-expressions-conditions/YR_CPP_in_SET_TRACE_expression.CPP \
		src/yr-expressions-conditions/YR_CPP_not_in_SET_TRACE_expression.CPP
QMAKE_TARGET  = yr_sd_runtime_verif
DESTDIR       = lib/
TARGET        = libyr_sd_runtime_verif.a


first: all
####### Build rules

staticlib: lib/$(TARGET)

lib/libyr_sd_runtime_verif.a:  $(OBJECTS) $(OBJCOMP) 
	@test -d lib/ || mkdir -p lib/
	-$(DEL_FILE) lib/$(TARGET)
	$(AR) $(DESTDIR)$(TARGET) $(OBJECTS)


Makefile: yr_sd_runtime_verif.pro /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_charts.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_designer.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_help.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmlmodels.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_svg.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uitools.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_x11extras.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		config.pri \
		lib.pri \
		yr_sd_runtime_verif.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		yr_sd_runtime_verif.pro
	$(QMAKE) -o Makefile yr_sd_runtime_verif.pro
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_charts.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_designer.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_help.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmlmodels.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmlworkerscript.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_svg.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uiplugin.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uitools.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_x11extras.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf:
.qmake.stash:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf:
config.pri:
lib.pri:
yr_sd_runtime_verif.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf:
yr_sd_runtime_verif.pro:
qmake: FORCE
	@$(QMAKE) -o Makefile yr_sd_runtime_verif.pro

qmake_all: FORCE


all: Makefile lib/libyr_sd_runtime_verif.a

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents src/YR_CPP_MONITOR.hpp src/YR_CPP_MONITOR_EDGE.hpp src/YR_CPP_MONITOR_EVENT.hpp src/YR_CPP_MONITOR_object.hpp src/YR_CPP_MONITOR_STATE.hpp src/YR_CPP_MONITOR_TRACE_EVENT.hpp src/utils/YR_CPP_MONITOR_ERP-database.hpp src/utils/YR_CPP_UTILS.hpp src/yr-expressions-conditions/YR_CPP_BOOLEAN_expression.HPP src/yr-expressions-conditions/YR_CPP_expression.HPP src/yr-expressions-conditions/YR_CPP_in_SET_TRACE_expression.HPP src/yr-expressions-conditions/YR_CPP_not_in_SET_TRACE_expression.HPP $(DISTDIR)/
	$(COPY_FILE) --parents src/YR_CPP_MONITOR.cpp src/YR_CPP_MONITOR_EDGE.cpp src/YR_CPP_MONITOR_EVENT.cpp src/YR_CPP_MONITOR_object.cpp src/YR_CPP_MONITOR_STATE.cpp src/YR_CPP_MONITOR_TRACE_EVENT.cpp src/utils/YR_CPP_MONITOR_ERP-database.cpp src/utils/YR_CPP_UTILS.cpp src/yr-expressions-conditions/YR_CPP_BOOLEAN_expression.CPP src/yr-expressions-conditions/YR_CPP_expression.CPP src/yr-expressions-conditions/YR_CPP_in_SET_TRACE_expression.CPP src/yr-expressions-conditions/YR_CPP_not_in_SET_TRACE_expression.CPP $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) lib/$(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: _generated/moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) _generated/moc_predefs.h
_generated/moc_predefs.h: /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp
	g++ -pipe -Wno-unused-variable -Wno-unused-parameter -Wno-misleading-indentation -isystem -Wno-unused-variable -Wno-unused-parameter -Wno-misleading-indentation -isystem -O2 -fPIC -std=gnu++1y -Wall -Wextra -dM -E -o _generated/moc_predefs.h /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: _generated/moc_YR_CPP_MONITOR.cpp _generated/moc_YR_CPP_MONITOR_EDGE.cpp _generated/moc_YR_CPP_MONITOR_EVENT.cpp _generated/moc_YR_CPP_MONITOR_object.cpp _generated/moc_YR_CPP_MONITOR_STATE.cpp _generated/moc_YR_CPP_MONITOR_TRACE_EVENT.cpp _generated/moc_YR_CPP_UTILS.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) _generated/moc_YR_CPP_MONITOR.cpp _generated/moc_YR_CPP_MONITOR_EDGE.cpp _generated/moc_YR_CPP_MONITOR_EVENT.cpp _generated/moc_YR_CPP_MONITOR_object.cpp _generated/moc_YR_CPP_MONITOR_STATE.cpp _generated/moc_YR_CPP_MONITOR_TRACE_EVENT.cpp _generated/moc_YR_CPP_UTILS.cpp
_generated/moc_YR_CPP_MONITOR.cpp: src/YR_CPP_MONITOR.hpp \
		src/utils/YR_CPP_UTILS.hpp \
		src/yr-expressions-conditions/YR_CPP_in_SET_TRACE_expression.HPP \
		src/yr-expressions-conditions/YR_CPP_BOOLEAN_expression.HPP \
		src/YR_CPP_MONITOR_object.hpp \
		_generated/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/yer/yr_sd_runtime_verif/_generated/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/yer/yr_sd_runtime_verif -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtOpenGL -I/usr/include/x86_64-linux-gnu/qt5/QtPrintSupport -I/usr/include/x86_64-linux-gnu/qt5/QtSvg -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtXml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/10 -I/usr/include/x86_64-linux-gnu/c++/10 -I/usr/include/c++/10/backward -I/usr/lib/gcc/x86_64-linux-gnu/10/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/YR_CPP_MONITOR.hpp -o _generated/moc_YR_CPP_MONITOR.cpp

_generated/moc_YR_CPP_MONITOR_EDGE.cpp: src/YR_CPP_MONITOR_EDGE.hpp \
		src/utils/YR_CPP_UTILS.hpp \
		src/yr-expressions-conditions/YR_CPP_in_SET_TRACE_expression.HPP \
		src/yr-expressions-conditions/YR_CPP_BOOLEAN_expression.HPP \
		src/YR_CPP_MONITOR_object.hpp \
		src/YR_CPP_MONITOR.hpp \
		src/YR_CPP_MONITOR_EVENT.hpp \
		_generated/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/yer/yr_sd_runtime_verif/_generated/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/yer/yr_sd_runtime_verif -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtOpenGL -I/usr/include/x86_64-linux-gnu/qt5/QtPrintSupport -I/usr/include/x86_64-linux-gnu/qt5/QtSvg -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtXml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/10 -I/usr/include/x86_64-linux-gnu/c++/10 -I/usr/include/c++/10/backward -I/usr/lib/gcc/x86_64-linux-gnu/10/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/YR_CPP_MONITOR_EDGE.hpp -o _generated/moc_YR_CPP_MONITOR_EDGE.cpp

_generated/moc_YR_CPP_MONITOR_EVENT.cpp: src/YR_CPP_MONITOR_EVENT.hpp \
		src/utils/YR_CPP_UTILS.hpp \
		src/yr-expressions-conditions/YR_CPP_in_SET_TRACE_expression.HPP \
		src/yr-expressions-conditions/YR_CPP_BOOLEAN_expression.HPP \
		src/YR_CPP_MONITOR_object.hpp \
		_generated/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/yer/yr_sd_runtime_verif/_generated/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/yer/yr_sd_runtime_verif -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtOpenGL -I/usr/include/x86_64-linux-gnu/qt5/QtPrintSupport -I/usr/include/x86_64-linux-gnu/qt5/QtSvg -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtXml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/10 -I/usr/include/x86_64-linux-gnu/c++/10 -I/usr/include/c++/10/backward -I/usr/lib/gcc/x86_64-linux-gnu/10/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/YR_CPP_MONITOR_EVENT.hpp -o _generated/moc_YR_CPP_MONITOR_EVENT.cpp

_generated/moc_YR_CPP_MONITOR_object.cpp: src/YR_CPP_MONITOR_object.hpp \
		src/utils/YR_CPP_UTILS.hpp \
		src/yr-expressions-conditions/YR_CPP_in_SET_TRACE_expression.HPP \
		src/yr-expressions-conditions/YR_CPP_BOOLEAN_expression.HPP \
		_generated/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/yer/yr_sd_runtime_verif/_generated/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/yer/yr_sd_runtime_verif -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtOpenGL -I/usr/include/x86_64-linux-gnu/qt5/QtPrintSupport -I/usr/include/x86_64-linux-gnu/qt5/QtSvg -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtXml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/10 -I/usr/include/x86_64-linux-gnu/c++/10 -I/usr/include/c++/10/backward -I/usr/lib/gcc/x86_64-linux-gnu/10/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/YR_CPP_MONITOR_object.hpp -o _generated/moc_YR_CPP_MONITOR_object.cpp

_generated/moc_YR_CPP_MONITOR_STATE.cpp: src/YR_CPP_MONITOR_STATE.hpp \
		src/utils/YR_CPP_UTILS.hpp \
		src/yr-expressions-conditions/YR_CPP_in_SET_TRACE_expression.HPP \
		src/yr-expressions-conditions/YR_CPP_BOOLEAN_expression.HPP \
		src/YR_CPP_MONITOR_object.hpp \
		_generated/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/yer/yr_sd_runtime_verif/_generated/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/yer/yr_sd_runtime_verif -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtOpenGL -I/usr/include/x86_64-linux-gnu/qt5/QtPrintSupport -I/usr/include/x86_64-linux-gnu/qt5/QtSvg -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtXml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/10 -I/usr/include/x86_64-linux-gnu/c++/10 -I/usr/include/c++/10/backward -I/usr/lib/gcc/x86_64-linux-gnu/10/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/YR_CPP_MONITOR_STATE.hpp -o _generated/moc_YR_CPP_MONITOR_STATE.cpp

_generated/moc_YR_CPP_MONITOR_TRACE_EVENT.cpp: src/YR_CPP_MONITOR_TRACE_EVENT.hpp \
		src/utils/YR_CPP_UTILS.hpp \
		src/yr-expressions-conditions/YR_CPP_in_SET_TRACE_expression.HPP \
		src/yr-expressions-conditions/YR_CPP_BOOLEAN_expression.HPP \
		src/YR_CPP_MONITOR_object.hpp \
		_generated/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/yer/yr_sd_runtime_verif/_generated/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/yer/yr_sd_runtime_verif -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtOpenGL -I/usr/include/x86_64-linux-gnu/qt5/QtPrintSupport -I/usr/include/x86_64-linux-gnu/qt5/QtSvg -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtXml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/10 -I/usr/include/x86_64-linux-gnu/c++/10 -I/usr/include/c++/10/backward -I/usr/lib/gcc/x86_64-linux-gnu/10/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/YR_CPP_MONITOR_TRACE_EVENT.hpp -o _generated/moc_YR_CPP_MONITOR_TRACE_EVENT.cpp

_generated/moc_YR_CPP_UTILS.cpp: src/utils/YR_CPP_UTILS.hpp \
		src/yr-expressions-conditions/YR_CPP_in_SET_TRACE_expression.HPP \
		src/yr-expressions-conditions/YR_CPP_BOOLEAN_expression.HPP \
		_generated/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/yer/yr_sd_runtime_verif/_generated/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/yer/yr_sd_runtime_verif -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtOpenGL -I/usr/include/x86_64-linux-gnu/qt5/QtPrintSupport -I/usr/include/x86_64-linux-gnu/qt5/QtSvg -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtXml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/10 -I/usr/include/x86_64-linux-gnu/c++/10 -I/usr/include/c++/10/backward -I/usr/lib/gcc/x86_64-linux-gnu/10/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/utils/YR_CPP_UTILS.hpp -o _generated/moc_YR_CPP_UTILS.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean compiler_moc_header_clean 

####### Compile

_generated/YR_CPP_MONITOR.o: src/YR_CPP_MONITOR.cpp src/YR_CPP_MONITOR.hpp \
		src/utils/YR_CPP_UTILS.hpp \
		src/yr-expressions-conditions/YR_CPP_in_SET_TRACE_expression.HPP \
		src/yr-expressions-conditions/YR_CPP_BOOLEAN_expression.HPP \
		src/YR_CPP_MONITOR_object.hpp \
		src/YR_CPP_MONITOR_EDGE.hpp \
		src/YR_CPP_MONITOR_EVENT.hpp \
		src/YR_CPP_MONITOR_STATE.hpp \
		src/utils/YR_CPP_MONITOR_ERP-database.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o _generated/YR_CPP_MONITOR.o src/YR_CPP_MONITOR.cpp

_generated/YR_CPP_MONITOR_EDGE.o: src/YR_CPP_MONITOR_EDGE.cpp src/YR_CPP_MONITOR_EDGE.hpp \
		src/utils/YR_CPP_UTILS.hpp \
		src/yr-expressions-conditions/YR_CPP_in_SET_TRACE_expression.HPP \
		src/yr-expressions-conditions/YR_CPP_BOOLEAN_expression.HPP \
		src/YR_CPP_MONITOR_object.hpp \
		src/YR_CPP_MONITOR.hpp \
		src/YR_CPP_MONITOR_EVENT.hpp \
		src/YR_CPP_MONITOR_STATE.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o _generated/YR_CPP_MONITOR_EDGE.o src/YR_CPP_MONITOR_EDGE.cpp

_generated/YR_CPP_MONITOR_EVENT.o: src/YR_CPP_MONITOR_EVENT.cpp src/YR_CPP_MONITOR_EVENT.hpp \
		src/utils/YR_CPP_UTILS.hpp \
		src/yr-expressions-conditions/YR_CPP_in_SET_TRACE_expression.HPP \
		src/yr-expressions-conditions/YR_CPP_BOOLEAN_expression.HPP \
		src/YR_CPP_MONITOR_object.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o _generated/YR_CPP_MONITOR_EVENT.o src/YR_CPP_MONITOR_EVENT.cpp

_generated/YR_CPP_MONITOR_object.o: src/YR_CPP_MONITOR_object.cpp src/YR_CPP_MONITOR_object.hpp \
		src/utils/YR_CPP_UTILS.hpp \
		src/yr-expressions-conditions/YR_CPP_in_SET_TRACE_expression.HPP \
		src/yr-expressions-conditions/YR_CPP_BOOLEAN_expression.HPP
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o _generated/YR_CPP_MONITOR_object.o src/YR_CPP_MONITOR_object.cpp

_generated/YR_CPP_MONITOR_STATE.o: src/YR_CPP_MONITOR_STATE.cpp src/YR_CPP_MONITOR_STATE.hpp \
		src/utils/YR_CPP_UTILS.hpp \
		src/yr-expressions-conditions/YR_CPP_in_SET_TRACE_expression.HPP \
		src/yr-expressions-conditions/YR_CPP_BOOLEAN_expression.HPP \
		src/YR_CPP_MONITOR_object.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o _generated/YR_CPP_MONITOR_STATE.o src/YR_CPP_MONITOR_STATE.cpp

_generated/YR_CPP_MONITOR_TRACE_EVENT.o: src/YR_CPP_MONITOR_TRACE_EVENT.cpp src/YR_CPP_MONITOR_TRACE_EVENT.hpp \
		src/utils/YR_CPP_UTILS.hpp \
		src/yr-expressions-conditions/YR_CPP_in_SET_TRACE_expression.HPP \
		src/yr-expressions-conditions/YR_CPP_BOOLEAN_expression.HPP \
		src/YR_CPP_MONITOR_object.hpp \
		src/YR_CPP_MONITOR_EVENT.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o _generated/YR_CPP_MONITOR_TRACE_EVENT.o src/YR_CPP_MONITOR_TRACE_EVENT.cpp

_generated/YR_CPP_MONITOR_ERP-database.o: src/utils/YR_CPP_MONITOR_ERP-database.cpp src/utils/YR_CPP_MONITOR_ERP-database.hpp \
		src/utils/YR_CPP_UTILS.hpp \
		src/yr-expressions-conditions/YR_CPP_in_SET_TRACE_expression.HPP \
		src/yr-expressions-conditions/YR_CPP_BOOLEAN_expression.HPP
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o _generated/YR_CPP_MONITOR_ERP-database.o src/utils/YR_CPP_MONITOR_ERP-database.cpp

_generated/YR_CPP_UTILS.o: src/utils/YR_CPP_UTILS.cpp src/utils/YR_CPP_UTILS.hpp \
		src/yr-expressions-conditions/YR_CPP_in_SET_TRACE_expression.HPP \
		src/yr-expressions-conditions/YR_CPP_BOOLEAN_expression.HPP
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o _generated/YR_CPP_UTILS.o src/utils/YR_CPP_UTILS.cpp

_generated/YR_CPP_BOOLEAN_expression.o: src/yr-expressions-conditions/YR_CPP_BOOLEAN_expression.CPP src/yr-expressions-conditions/YR_CPP_BOOLEAN_expression.HPP \
		src/YR_CPP_MONITOR_EVENT.hpp \
		src/utils/YR_CPP_UTILS.hpp \
		src/yr-expressions-conditions/YR_CPP_in_SET_TRACE_expression.HPP \
		src/YR_CPP_MONITOR_object.hpp
	$(CC) -c $(CFLAGS) $(INCPATH) -o _generated/YR_CPP_BOOLEAN_expression.o src/yr-expressions-conditions/YR_CPP_BOOLEAN_expression.CPP

_generated/YR_CPP_expression.o: src/yr-expressions-conditions/YR_CPP_expression.CPP src/yr-expressions-conditions/YR_CPP_expression.HPP \
		src/YR_CPP_MONITOR_EVENT.hpp \
		src/utils/YR_CPP_UTILS.hpp \
		src/yr-expressions-conditions/YR_CPP_in_SET_TRACE_expression.HPP \
		src/yr-expressions-conditions/YR_CPP_BOOLEAN_expression.HPP \
		src/YR_CPP_MONITOR_object.hpp
	$(CC) -c $(CFLAGS) $(INCPATH) -o _generated/YR_CPP_expression.o src/yr-expressions-conditions/YR_CPP_expression.CPP

_generated/YR_CPP_in_SET_TRACE_expression.o: src/yr-expressions-conditions/YR_CPP_in_SET_TRACE_expression.CPP src/yr-expressions-conditions/YR_CPP_in_SET_TRACE_expression.HPP \
		src/yr-expressions-conditions/YR_CPP_BOOLEAN_expression.HPP \
		src/YR_CPP_MONITOR_TRACE_EVENT.hpp \
		src/utils/YR_CPP_UTILS.hpp \
		src/YR_CPP_MONITOR_object.hpp \
		src/YR_CPP_MONITOR_EVENT.hpp
	$(CC) -c $(CFLAGS) $(INCPATH) -o _generated/YR_CPP_in_SET_TRACE_expression.o src/yr-expressions-conditions/YR_CPP_in_SET_TRACE_expression.CPP

_generated/YR_CPP_not_in_SET_TRACE_expression.o: src/yr-expressions-conditions/YR_CPP_not_in_SET_TRACE_expression.CPP src/yr-expressions-conditions/YR_CPP_not_in_SET_TRACE_expression.HPP \
		src/yr-expressions-conditions/YR_CPP_in_SET_TRACE_expression.HPP \
		src/yr-expressions-conditions/YR_CPP_BOOLEAN_expression.HPP \
		src/YR_CPP_MONITOR_TRACE_EVENT.hpp \
		src/utils/YR_CPP_UTILS.hpp \
		src/YR_CPP_MONITOR_object.hpp \
		src/YR_CPP_MONITOR_EVENT.hpp
	$(CC) -c $(CFLAGS) $(INCPATH) -o _generated/YR_CPP_not_in_SET_TRACE_expression.o src/yr-expressions-conditions/YR_CPP_not_in_SET_TRACE_expression.CPP

_generated/moc_YR_CPP_MONITOR.o: _generated/moc_YR_CPP_MONITOR.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o _generated/moc_YR_CPP_MONITOR.o _generated/moc_YR_CPP_MONITOR.cpp

_generated/moc_YR_CPP_MONITOR_EDGE.o: _generated/moc_YR_CPP_MONITOR_EDGE.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o _generated/moc_YR_CPP_MONITOR_EDGE.o _generated/moc_YR_CPP_MONITOR_EDGE.cpp

_generated/moc_YR_CPP_MONITOR_EVENT.o: _generated/moc_YR_CPP_MONITOR_EVENT.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o _generated/moc_YR_CPP_MONITOR_EVENT.o _generated/moc_YR_CPP_MONITOR_EVENT.cpp

_generated/moc_YR_CPP_MONITOR_object.o: _generated/moc_YR_CPP_MONITOR_object.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o _generated/moc_YR_CPP_MONITOR_object.o _generated/moc_YR_CPP_MONITOR_object.cpp

_generated/moc_YR_CPP_MONITOR_STATE.o: _generated/moc_YR_CPP_MONITOR_STATE.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o _generated/moc_YR_CPP_MONITOR_STATE.o _generated/moc_YR_CPP_MONITOR_STATE.cpp

_generated/moc_YR_CPP_MONITOR_TRACE_EVENT.o: _generated/moc_YR_CPP_MONITOR_TRACE_EVENT.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o _generated/moc_YR_CPP_MONITOR_TRACE_EVENT.o _generated/moc_YR_CPP_MONITOR_TRACE_EVENT.cpp

_generated/moc_YR_CPP_UTILS.o: _generated/moc_YR_CPP_UTILS.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o _generated/moc_YR_CPP_UTILS.o _generated/moc_YR_CPP_UTILS.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

