

YR_SD_RUNTIME_VERIF="yr_sd_runtime_verif"

YR_SD_RUNTIME_VERIF_SUT="${HOME}/${YR_SD_RUNTIME_VERIF}"

YR_SD_RUNTIME_VERIF_UT_HOME_DEVEL="${HOME}/yr_sd_runtime_verif_UNIT_TESTS"

SRC="src"

mkdir -p "${YR_SD_RUNTIME_VERIF_UT_HOME_DEVEL}/${YR_SD_RUNTIME_VERIF}"

cp -r ${YR_SD_RUNTIME_VERIF_SUT}/* ${YR_SD_RUNTIME_VERIF_UT_HOME_DEVEL}/${YR_SD_RUNTIME_VERIF}


