

YR_SD_RUNTIME_VERIF="yr_sd_runtime_verif"

YR_SD_RUNTIME_VERIF_LIB_HOME="${HOME}/${YR_SD_RUNTIME_VERIF}"

YR_SD_RUNTIME_VERIF_UT_HOME_DEVEL="${HOME}/yr_sd_runtime_verif_UNIT_TESTS"

SRC="src"

set -x

rm -r "${YR_SD_RUNTIME_VERIF_UT_HOME_DEVEL}/${YR_SD_RUNTIME_VERIF}"

mkdir -p "${YR_SD_RUNTIME_VERIF_UT_HOME_DEVEL}/${YR_SD_RUNTIME_VERIF}"


cp -r ${YR_SD_RUNTIME_VERIF_LIB_HOME}/lib ${YR_SD_RUNTIME_VERIF_UT_HOME_DEVEL}/${YR_SD_RUNTIME_VERIF}

cp -r ${YR_SD_RUNTIME_VERIF_LIB_HOME}/src/* ${YR_SD_RUNTIME_VERIF_UT_HOME_DEVEL}/${YR_SD_RUNTIME_VERIF}


